[workspace]
members = ["qoqo-quest", "roqoqo-quest", "quest-sys"]

resolver = "2"

[profile.release]
lto = true

[profile.bench]
lto = true

[patch.crates-io]
roqoqo = { path = "/home/rreiner/HQS/forks/qoqo/roqoqo" }
qoqo = { path = "/home/rreiner/HQS/forks/qoqo/qoqo" }
